#! /bin/sh

xrc param/latest

aaa(){
    param:dsl <<A
option:
    -y|--fsdfsd|-o          "Test regex arg1"       <regex_arg1>=888  =~  "[0-9]+"
    -n                      "Test regex arg2"       <regex_arg1>=123  =~  "[0-9]+"
    -s                      "Test regex arg3"       <regex_arg1>=333  =~  "[0-9]+"
    --d|-t                  "Test regex arg4"       <regex_arg1>=444  =~  "[0-9]+"
    --org                   "org space address"     <>:address
    --no_wiki               "Whether to disable wiki"
    --no_auto_init          "Disable auto init README"
A
    param:run

    # local no_issue=true
    new_option="xxx"
    k="kkk"
    p=""
    m="aaa"
    param:option2json has_issues=^no_issue has_wiki=^no_wiki can_comment=^no_comment auto_init=^no_auto_init new_option repoitory l=^^k o=^^p +m -n
    # param:option2json
    # echo "\nhas_issues: $has_issues\nhas_wiki: $has_wiki\ncan_comment: $can_comment\nauto_init: $auto_init\nnew_option: $new_option\nrepoitory: $repoitory\nl: $l\no: $o\ny: $y\nm: $m\ns: $s\n"
    # param:flag2bool has_issues=^no_issue
    # echo "\nhas_issues: $has_issues"
}
aaa --org test --no_wiki