# Do NOT modify manually for this file is auto generated by command: x boot setup

if command -v xrc >/dev/null 2>&1; then
    return 0
elif [ -f "$HOME/.x-cmd/xrc/latest" ]; then
    . "$HOME/.x-cmd/xrc/latest"
else
    printf "%s\n  %s" 'xrc/latest not found. You can reinstall using:' 'eval "\$(curl https://get.x-cmd.com)"'
    return 1
fi

xrc env/latest
[ -f "$HOME/.x-cmd/.boot/mod" ] && x boot mod load
[ -f "$HOME/.x-cmd/.boot/rc" ] && . "$HOME/.x-cmd/.boot/rc"
: