name: 'github actions publish x-cmd/dev'

on:
  schedule:
    - cron: '30 11 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: install x-cmd
        run:  eval "$(curl https://get.x-cmd.com/dev)"
      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: setup ssh
        run:  x gh-action ssh "$SSH_PRIVATE_KEY" agent-0 0@x-cmd.com
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: publish
        run: xws pub
