name: 'github actions publish x-cmd/dev'

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 11 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: install x-cmd && setup ssh publish
        uses: x-cmd/checkout
        with:
          ref: main
          sshkey: ${{ secrets.SSH_PRIVATE_KEY }}
          user/email: agent-zero/0@x-cmd.com
        run: xws pub0
