name: Publish-Cron-Debug
on:
  push:
  workflow_dispatch:

jobs:
  publisher:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      ___X_CMD_CODESORUCE_REPO: dev
      ___X_CMD_LOG_C_TF: 1
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x log +yanfa && x ws pub || true; echo $___X_CMD_LOG_C_TF
          # code: x ws pub || true
